<a href="https://colab.research.google.com/github/Pigwen/hands-on-sft/blob/main/CHAPTER_2_Loading_a_Quantized_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pre-Reqs

模型参数量到内存占用量的(大致)转换公式
```
model_size_in_mb = (num_params * (bits_per_param / 8)) / 1e6
```

# Quantization in a Nutsshell

量化本质就是分箱，步骤和直方图类似：
* 定义FP32数字的可能范围
* 将其均匀的分成若干个箱子
* 对于每一个数，确定对应的区间(箱子)，并赋予其区间(箱子)id

In [1]:
import torch

torch.manual_seed(11)
weights = torch.randn(1000) * .07
weights.min(), weights.max()

(tensor(-0.2066), tensor(0.2097))

In [2]:
n_bins = 4
bins = torch.linspace(weights.min(), weights.max(), n_bins+1)
bin_width = bins[1] - bins[0]
bins, bin_width

(tensor([-0.2066, -0.1026,  0.0015,  0.1056,  0.2097]), tensor(0.1041))

In [3]:
bin_indexs = ((weights.view(-1, 1) > bins).to(torch.int).argmin(dim=-1) - 1)
print(weights[:20], bin_indexs[:20])

tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048,  0.0099, -0.0367,
        -0.0174, -0.0368,  0.2025, -0.0416,  0.0918,  0.0247, -0.0921, -0.0006,
         0.0174,  0.1101, -0.1148, -0.1115]) tensor([1, 2, 1, 2, 1, 0, 2, 1, 1, 1, 3, 1, 2, 2, 1, 1, 2, 3, 0, 0])


In [4]:
bin_values = bins[:-1]
first_bin = bin_values[0]
bin_values

tensor([-0.2066, -0.1026,  0.0015,  0.1056])

In [5]:
approx_values = bin_indexs * bin_width + first_bin
print(approx_values[:20])

tensor([-0.1026,  0.0015, -0.1026,  0.0015, -0.1026, -0.2066,  0.0015, -0.1026,
        -0.1026, -0.1026,  0.1056, -0.1026,  0.0015,  0.0015, -0.1026, -0.1026,
         0.0015,  0.1056, -0.2066, -0.2066])


In [6]:
print(weights[:20])

tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048,  0.0099, -0.0367,
        -0.0174, -0.0368,  0.2025, -0.0416,  0.0918,  0.0247, -0.0921, -0.0006,
         0.0174,  0.1101, -0.1148, -0.1115])


In [7]:
from torch import nn

mse_fn = nn.MSELoss()
mse_fn(approx_values, weights).sqrt()

tensor(0.0615)

In [8]:
def quantize(weights: torch.Tensor, n_bits: int = 8):
  assert n_bits <= 16

  n_bins = 2 ** n_bits
  bins = torch.linspace(weights.min(), weights.max(), n_bins+1)
  first_bin = bins[0]
  bin_width = bins[1] - first_bin
  bin_index = (weights.view(-1, 1) > bins).to(torch.int).argmin(dim=-1)
  return bin_index, bin_width, first_bin

def dequantize(bin_index: torch.Tensor, bin_width: float, first_bin: float):
  return bin_index * bin_width + first_bin


In [9]:
for i in [2, 4, 6, 8, 16]:
  res = quantize(weights, i)
  approx_values = dequantize(*res)
  print(f"{i} bits quantization")
  print(f"approx: {approx_values[:6]}")
  print(f"weights: {weights[:6]}")
  print(f"loss: {mse_fn(approx_values, weights).sqrt()}\n")

2 bits quantization
approx: tensor([ 0.0015,  0.1056,  0.0015,  0.1056,  0.0015, -0.1026])
weights: tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048])
loss: 0.059067390859127045

4 bits quantization
approx: tensor([-0.0245,  0.0796, -0.0245,  0.0275,  0.0015, -0.1026])
weights: tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048])
loss: 0.014644436538219452

6 bits quantization
approx: tensor([-0.0310,  0.0731, -0.0245,  0.0145, -0.0115, -0.1026])
weights: tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048])
loss: 0.003786345012485981

8 bits quantization
approx: tensor([-0.0343,  0.0731, -0.0245,  0.0096, -0.0115, -0.1042])
weights: tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048])
loss: 0.000910897389985621

16 bits quantization
approx: tensor([-0.0359,  0.0718, -0.0248,  0.0085, -0.0128, -0.1049])
weights: tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048])
loss: 0.00013679217954631895



# Half-Precision Weights

In [10]:
fp16_weights = weights.to(torch.float16)
print(fp16_weights[:6])
print(weights[:6])

tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048],
       dtype=torch.float16)
tensor([-0.0358,  0.0720, -0.0247,  0.0086, -0.0127, -0.1048])


In [11]:
print(mse_fn(fp16_weights, weights).sqrt())

tensor(1.4244e-05)


## Living on the Edge

In [12]:
torch.manual_seed(14)
tiny_values = torch.randn(1000) * 1e-5
fp16_tiny_values = tiny_values.to(torch.float16)
mse_fn(fp16_tiny_values, tiny_values)

tensor(2.8526e-16)

In [13]:
print(tiny_values[155:160])
print(fp16_tiny_values[155:160])

tensor([-2.7241e-06,  1.1441e-05,  3.7199e-06, -1.1252e-06, -2.4735e-08])
tensor([-2.7418e-06,  1.1444e-05,  3.6955e-06, -1.1325e-06, -0.0000e+00],
       dtype=torch.float16)


In [14]:
torch.manual_seed(19)
large_values = torch.randn(1000) * 1e5
fp16_large_values = large_values.to(torch.float16)
print(large_values[:5])
print(fp16_large_values[:5])

tensor([155074.0938,  64881.6602,   2729.5815, -40790.6562,  68846.7188])
tensor([    inf,  64896.,   2730., -40800.,     inf], dtype=torch.float16)


In [15]:
fp16_info = torch.finfo(torch.float16)
fp16_info

finfo(resolution=0.001, min=-65504, max=65504, eps=0.000976562, smallest_normal=6.10352e-05, tiny=6.10352e-05, dtype=float16)

In [16]:
bf16_info = torch.finfo(torch.bfloat16)
print(bf16_info)
print(fp16_info)

finfo(resolution=0.01, min=-3.38953e+38, max=3.38953e+38, eps=0.0078125, smallest_normal=1.17549e-38, tiny=1.17549e-38, dtype=bfloat16)
finfo(resolution=0.001, min=-65504, max=65504, eps=0.000976562, smallest_normal=6.10352e-05, tiny=6.10352e-05, dtype=float16)


In [17]:
fp32_info = torch.finfo(torch.float32)
print(fp32_info)
print(bf16_info)

finfo(resolution=1e-06, min=-3.40282e+38, max=3.40282e+38, eps=1.19209e-07, smallest_normal=1.17549e-38, tiny=1.17549e-38, dtype=float32)
finfo(resolution=0.01, min=-3.38953e+38, max=3.38953e+38, eps=0.0078125, smallest_normal=1.17549e-38, tiny=1.17549e-38, dtype=bfloat16)


# Loading Models

In [18]:
from collections import Counter
from transformers import AutoModelForCausalLM

def get_param_dtypes(iterable, top_k=3):
  return Counter([i.dtype for i in iterable]).most_common(top_k)

model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m", device_map="auto")
print(model.get_memory_footprint()/1e6, get_param_dtypes(model.parameters()))

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


1324.785664 [(torch.float32, 388)]


In [19]:
import torch
from transformers import AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("facebook/opt-350m", device_map="auto", dtype=torch.float32)

tokenizer = AutoTokenizer.from_pretrained("facebook/opt-350m")
batch = tokenizer(["This is a simple test"], return_tensors="pt")

batch["labels"] = batch["input_ids"] # 用于计算loss
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device is {device}")
batch = {k: v.to(device) for k, v in batch.items()}
output = model(**batch)
output.loss



device is cuda


tensor(3.8001, device='cuda:0', grad_fn=<NllLossBackward0>)

## Half-Precision Models(16-bit)

In [20]:
supported = torch.cuda.is_bf16_supported(including_emulation=False)
dtype16 = torch.bfloat16 if supported else torch.float16
dtype16

torch.float16

In [21]:
model.to(dtype16)
print(model.get_memory_footprint()/1e6, get_param_dtypes(model.parameters()))

662.392832 [(torch.float16, 388)]


# Mixed Precision

In [22]:
import torch
from torch import nn

class MixedModel(nn.Module):

  def __init__(self, dtype):
    super().__init__()
    self.a = nn.Linear(1000, 1000, dtype=dtype)
    self.b = nn.Linear(1000, 1000, dtype=dtype)

  def forward(self, x):
    return self.b(self.a(x))

In [23]:
mixed32 = MixedModel(torch.float32)
mixed32.to("cuda")

MixedModel(
  (a): Linear(in_features=1000, out_features=1000, bias=True)
  (b): Linear(in_features=1000, out_features=1000, bias=True)
)

In [24]:
%timeit mixed32(torch.randn(1000, 1000, dtype=torch.float32, device="cuda"))

1.18 ms ± 8.06 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [25]:
mixed16 = MixedModel(torch.float16).to("cuda")

In [26]:
%timeit mixed16(torch.randn(1000, 1000, dtype=torch.float16, device="cuda"))

218 µs ± 970 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
with torch.autocast(dtype=torch.float16, device_type="cuda"):
  %timeit mixed32(torch.randn(1000, 1000, device="cuda", dtype=torch.float32))

234 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
with torch.autocast(dtype=torch.float16, device_type="cuda"):
  res16 = mixed32(torch.randn(1000, 1000, device="cuda", dtype=torch.float32))

res32 = res16.float()

In [29]:
from types import MethodType

autocast_context = torch.autocast(dtype=torch.float16, device_type="cuda")
model_forward_func = mixed32.forward.__func__
new_forward = autocast_context(model_forward_func)
mixed32.forward = MethodType(new_forward, mixed32)


In [30]:
res = mixed32(torch.randn(1000, 1000, device="cuda", dtype=torch.float32))
res.dtype

torch.float16

In [31]:
from accelerate.utils.operations import convert_outputs_to_fp32

mixed32.forward = MethodType(convert_outputs_to_fp32(mixed32.forward.__func__), mixed32)
res = mixed32(torch.randn(1000, 1000, dtype=torch.float32, device="cuda"))
res.dtype


torch.float32

In [32]:
%timeit mixed32(torch.randn(1000, 1000, dtype=torch.float32, device="cuda"))

318 µs ± 8.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# BitsAndBytes

In [33]:
from transformers import BitsAndBytesConfig

bnb_config = BitsAndBytesConfig()
bnb_config

BitsAndBytesConfig {
  "_load_in_4bit": false,
  "_load_in_8bit": false,
  "bnb_4bit_compute_dtype": "float32",
  "bnb_4bit_quant_storage": "uint8",
  "bnb_4bit_quant_type": "fp4",
  "bnb_4bit_use_double_quant": false,
  "llm_int8_enable_fp32_cpu_offload": false,
  "llm_int8_has_fp16_weight": false,
  "llm_int8_skip_modules": null,
  "llm_int8_threshold": 6.0,
  "load_in_4bit": false,
  "load_in_8bit": false,
  "quant_method": "bitsandbytes"
}

## 8-Bit Quantization

In [34]:
!pip install -U bitsandbytes transformers

In [35]:
bnb_config_q8 = BitsAndBytesConfig(load_in_8bit=True)
model_q8 = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-350m",
    device_map="auto",
    quantization_config=bnb_config_q8
)

print(model_q8.get_memory_footprint()/1e6, get_param_dtypes(model_q8.parameters()))

359.354368 [(torch.float16, 242), (torch.int8, 146)]


In [36]:
out = model_q8(**batch)
out.loss, out.loss.dtype

(tensor(3.8339, device='cuda:0', grad_fn=<NllLossBackward0>), torch.float32)

In [37]:
model_q8_32 = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-350m",
    dtype=torch.float32,
    device_map="auto",
    quantization_config=bnb_config_q8
)
print(model_q8_32.get_memory_footprint()/1e6, get_param_dtypes(model_q8.parameters()))


415.670272 [(torch.float16, 242), (torch.int8, 146)]


In [38]:
out = model_q8_32(**batch)
out.loss, out.loss.dtype

/usr/local/lib/python3.12/dist-packages/bitsandbytes/autograd/_functions.py:123: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")


(tensor(3.8012, device='cuda:0', grad_fn=<NllLossBackward0>), torch.float32)

### Quantized Linear Layers

In [39]:
dec_layer = model_q8_32.model.decoder.layers[0]
dec_layer

OPTDecoderLayer(
  (self_attn): OPTAttention(
    (k_proj): Linear8bitLt(in_features=1024, out_features=1024, bias=True)
    (v_proj): Linear8bitLt(in_features=1024, out_features=1024, bias=True)
    (q_proj): Linear8bitLt(in_features=1024, out_features=1024, bias=True)
    (out_proj): Linear8bitLt(in_features=1024, out_features=1024, bias=True)
  )
  (activation_fn): ReLU()
  (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
  (fc1): Linear8bitLt(in_features=1024, out_features=4096, bias=True)
  (fc2): Linear8bitLt(in_features=4096, out_features=1024, bias=True)
  (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
)

In [40]:
q8_layer = dec_layer.self_attn.k_proj
q8_layer

Linear8bitLt(in_features=1024, out_features=1024, bias=True)

In [41]:
q8_state = q8_layer.state_dict()
q8_state

OrderedDict([('weight',
              tensor([[ -67, -113,  -89,  ...,   65,  -16,  -87],
                      [  60,  120,   90,  ...,  -50,   32,   80],
                      [  47,  127,   86,  ...,  -34,    8,   90],
                      ...,
                      [ -65,   65,   34,  ...,  -64,   35,   64],
                      [  57,   67,   21,  ...,   63,  -64,  -64],
                      [ -64,   63,  -11,  ...,  -64,   34,   63]], device='cuda:0',
                     dtype=torch.int8)),
             ('bias',
              tensor([-0.0134,  0.0082,  0.0161,  ..., -0.0242, -0.0150,  0.0203],
                     device='cuda:0')),
             ('SCB',
              tensor([0.1250, 0.1252, 0.1250,  ..., 0.1252, 0.1250, 0.1254], device='cuda:0')),
             ('weight_format', tensor(0, dtype=torch.uint8))])

In [42]:
print(model.model.decoder.embed_tokens)
print(model.lm_head)

Embedding(50272, 512, padding_idx=1)
Linear(in_features=512, out_features=50272, bias=False)


In [43]:
torch.allclose(model.model.decoder.embed_tokens.weight, model.lm_head.weight)

True

In [44]:
from transformers import AutoConfig
from accelerate.utils.modeling import find_tied_parameters

config = AutoConfig.from_pretrained("facebook/opt-350m")
config.tie_word_embeddings, find_tied_parameters(model)

(True, [['lm_head.weight', 'model.decoder.embed_tokens.weight']])

In [45]:
from accelerate import init_empty_weights

with init_empty_weights():
  empty_model = AutoModelForCausalLM.from_config(config)

empty_model.lm_head.weight

Parameter containing:
tensor(..., device='meta', size=(50272, 512), dtype=torch.float16,
       requires_grad=True)

In [46]:
from transformers.integrations.bitsandbytes import get_keys_to_not_convert

skip_modules = get_keys_to_not_convert(empty_model)
skip_modules

['lm_head', 'model.decoder.embed_tokens']

In [47]:
for module in skip_modules:
  parm = next(model_q8_32.get_submodule(module).parameters())
  print(f"{module}: {parm.dtype}")

lm_head: torch.float32
model.decoder.embed_tokens: torch.float32


### llm_int8_skip_modules

In [48]:
bnb_config_skip = BitsAndBytesConfig(
        load_in_8bit=True, llm_int8_skip_modules=['o_proj', 'lm_head']
)
model_skip = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-350m", device_map='cuda:0', torch_dtype=torch.float32,
    quantization_config=bnb_config_skip
)

`torch_dtype` is deprecated! Use `dtype` instead!


### 8-bit Layers

In [49]:
from bitsandbytes.nn import Linear8bitLt

n_in = 10
n_out = 10

torch.manual_seed(11)

fp_layer = nn.Linear(n_in, n_out)

int8_layer = Linear8bitLt(n_in, n_out, has_fp16_weights=False)

int8_layer.load_state_dict(fp_layer.state_dict())
int8_layer.state_dict()

OrderedDict([('weight',
              tensor([[-0.2220, -0.0085,  0.3072, -0.2097,  0.0531,  0.1224,  0.0525, -0.2350,
                        0.0456,  0.2687],
                      [-0.1459,  0.1786, -0.1443, -0.0233,  0.1689,  0.0015, -0.2514,  0.1644,
                        0.1920,  0.1678],
                      [ 0.2346,  0.1411,  0.2128,  0.0519,  0.2147, -0.2786, -0.0433, -0.0364,
                       -0.1504,  0.0823],
                      [ 0.2388, -0.2134, -0.1620, -0.1023,  0.2433, -0.2680,  0.3099, -0.1933,
                       -0.0471, -0.0391],
                      [-0.1273,  0.2197, -0.0136, -0.1938, -0.1746,  0.0404,  0.0711, -0.1730,
                        0.0539, -0.1992],
                      [-0.0051,  0.1373, -0.0267, -0.0907, -0.0107,  0.1108, -0.1566,  0.0172,
                        0.2075, -0.0028],
                      [ 0.2082, -0.2857, -0.2640, -0.1436,  0.1704,  0.1908, -0.2350,  0.1187,
                       -0.0568,  0.0916],
                 

In [50]:
int8_layer = int8_layer.to("cuda")
int8_state = int8_layer.state_dict()
int8_state

OrderedDict([('weight',
              tensor([[ -92,   -4,  127,  -87,   22,   51,   22,  -97,   19,  111],
                      [ -74,   90,  -73,  -12,   85,    1, -127,   83,   97,   85],
                      [ 107,   64,   97,   24,   98, -127,  -20,  -17,  -69,   38],
                      [  98,  -87,  -66,  -42,  100, -110,  127,  -79,  -19,  -16],
                      [ -74,  127,   -8, -112, -101,   23,   41, -100,   31, -115],
                      [  -3,   84,  -16,  -56,   -7,   68,  -96,   11,  127,   -2],
                      [  93, -127, -117,  -64,   76,   85, -104,   53,  -25,   41],
                      [ 123, -127,   23,   79,   11,  -79,  -24,  -39,  102,  117],
                      [ -51, -127,  -41,  -71,  110,  122,   67,  -11, -125,    9],
                      [ -50,    1,  -60,  -13,   73,  127,  106,  -70,   84,   84]],
                     device='cuda:0', dtype=torch.int8)),
             ('bias',
              tensor([ 0.1269,  0.2999,  0.0252, -0.038

## 4-Bit Quantization